{% set name = "blackdoc" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7958065881412dc243fe809f8fa249fbb8a6731ae5f587c976ce803eaf886ac9

build:
  number: 0
  noarch: python
  entry_points:
    - blackdoc=blackdoc.__main__:main
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    - setuptools_scm >=3.4
    - tomli
  run:
    - black
    - importlib-metadata
    - more-itertools
    - python >=3.6
    - tomli

test:
  imports:
    - blackdoc
    - blackdoc.formats
  commands:
    - pip check
    - blackdoc --help
    - python -c 'from blackdoc import __version__; assert __version__ != "0.0.0"'
  requires:
    - pip

about:
  home: https://github.com/keewis/blackdoc
  summary: run black on documentation code snippets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
