{% set name = "blackdoc" %}
{% set version = "0.4.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0bdf7a4e7abc6ecc55514d2a8012ea025487292284c6978fe74c888c0405049

build:
  number: 0
  noarch: python
  entry_points:
    - blackdoc=blackdoc.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=7.0
    - tomli
  run:
    - black
    - more-itertools
    - python >={{ python_min }}
    - tomli
    - rich

test:
  imports:
    - blackdoc
    - blackdoc.formats
  commands:
    - pip check
    - blackdoc --help
    - python -c 'from blackdoc import __version__; assert __version__ == "{{ version }}"'
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/keewis/blackdoc
  summary: run black on documentation code snippets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
